# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Here we set the parts that would
# be re-used between services to an
# extension field
# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-default-isaac-lab-volumes: &default-isaac-lab-volumes
    # This overlay allows changes on the local files to
    # be reflected within the container immediately
  - type: bind
    source: ../${EXTENSION_NAME}
    target: ${DOCKER_ISAACLAB_RANSV2_PATH}

x-default-isaac-lab-deploy: &default-isaac-lab-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  # This service is the base Isaac Lab image
  isaac-lab-ransv2-base:
    profiles: [ "base" ]
    env_file: .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - BASE_IMAGE_NAME_ARG=${BASE_IMAGE_NAME}
        - BASE_IMAGE_TAG_ARG=${BASE_IMAGE_TAG}
        - ISAAC_SIM_IMAGE_NAME_ARG=${ISAAC_SIM_IMAGE_NAME}
        - ISAAC_SIM_IMAGE_TAG_ARG=${ISAAC_SIM_IMAGE_TAG}
        - PYTHON_VERSION_ARG=${PYTHON_VERSION}
        - TORCH_VERSION_ARG=${TORCH_VERSION}
        - TORCHVISION_VERSION_ARG=${TORCHVISION_VERSION}
        - TORCH_INDEX_URL_ARG=${TORCH_INDEX_URL}
        - ISAAC_SIM_VERSION_ARG=${ISAAC_SIM_VERSION}
        - ISAAC_SIM_EXTRA_INDEX_URL_ARG=${ISAAC_SIM_EXTRA_INDEX_URL}
        
        # - ISAACSIM_ROOT_PATH_ARG=${DOCKER_ISAACSIM_ROOT_PATH}
        # - ISAACLAB_PATH_ARG=${DOCKER_ISAACLAB_PATH}
        - ISAACLAB_RANSV2_PATH_ARG=${DOCKER_ISAACLAB_RANSV2_PATH}
        - EXTENSION_NAME_ARG=${EXTENSION_NAME}
        # - DOCKER_USER_HOME_ARG=${DOCKER_USER_HOME}
    image: isaac-lab-${DOCKER_NAME_SUFFIX-}
    container_name: isaac-lab-${DOCKER_NAME_SUFFIX-}
    volumes: *default-isaac-lab-volumes
    network_mode: host
    deploy: *default-isaac-lab-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
